### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/carlosp-11-post-instagram#1]
# Review

- [x] Tu .css debe estar abajo de todos los otros .css
- [x] Procura crear directorios para agrupar los recursos. Ej: \image \styles

![Captura desde 2023-07-20 15-31-03](https://github.com/4GeeksAcademy/carlosp-11-post-instagram/assets/45291267/6c2e98b6-20f3-46ef-a04c-cbad1e9514f3)

**Comment by carlosp-11** [comment]
Completado

**Comment by hchocobar** [comment]
Genial
